spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx
    password: xxx
    url: xxx
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  data:
    generate-count: 10000
    thread:
      use-num: 80
      core-num: 50
      max-num: 100
      keep-alive-time: 10
      block-queue-length: 10